Bring in CM resources for mkbootimg and vold support thanks guys!
Summary:
Still working on fixing these:

system/vold/VolumeManager.cpp:892:15: error: unused variable 'idLen' [-Werror,-Wunused-variable]

Looks like a -Werror flag slipped in somewhere

system/core: Add command NATIVE_WINDOW_SET_BUFFERS_SIZE

Add native window command to set user defined buffer size.

Change-Id: Ib500e65283706d860d62cb487720008d7331ce2d

system/core: Add command NATIVE_WINDOW_UPDATE_BUFFERS_GEOMETRY

Add native window command to update buffer buffer width, height
and format before queuing the buffer.

Change-Id: Ic133f89afb762cfce5084af820af5f9bad2a4a0b

audio: Squashed set of commits for QCOM audio features

system/core: Add audio enums for QCELP/EVRC feature support

- Added required enums for QCELP/EVRC features.

Change-Id: Ib6b2297ebc9cac785fec99c3c2c80b1ad9b774f6

system/core: Added changes required for tunnel mode recording

- EVRC and QCELP format values are interchanged, due to
  this EVRC/QCELP are not recording with proper header.
- Added preproc_ctl, evrc/qcelp for tunnel mode recording.

Change-Id: I93db3170895387bec43a62214aa5d65aaab40c87

system/core: Add output flag for LPA and Tunnel

Change-Id: I621818502c273b2c8aba37f64a83539450a1aafa

audio: VOIP bringup and support for vocoders.

Setup permissions for MVS driver.

Add vocoder types.

Change-Id: Ie150be9b01137628ba3e3ea788d429096ba1f413

system/core: Add enums for voice call recording.

Add enums for voice call recording

Change-Id: Idd5cd19573c48a0a782bcd56cca38b4901391bbf

system/core: Add support for surround sound recording

- Add 5.1 input channel definitions and masks

Change-Id: I24375c0d9443cd6e8dd58114464bf9f528b97d43

audio: Add a flag for VOIP RX

Change-Id: Iecb8c3a7b247c0a839b4b145574e2c4f35dbce64

include/system: JB upgrade for the MPQ8064

Include the flags for the MPQ8064.

Change-Id: Ic1bd11d341456a8b217d63cddbb19a9a92ee86c5

audio: Fix input enums for pre-4.2 audio blobs

Change-Id: Iec9f8d915d069168664d2cd873574db7fe5cddc7

audio: add QCOM supported audio devices

- Add ANC headset, FM, and proxy devices

Change-Id: Ib7b7495ed69ca3ab072c5512e9286da8d3538682
(cherry picked from commit fd629294bcaaa2cb70befc631f7596439d6cbe70)

audio: add support for QCOM audio formats

- Add support for EVRC, QCELP, and WMA formats

Change-Id: Id5f7845ff7bc609e947f93d8647ad3f3e57babfb
(cherry picked from commit 8b3476f14882afa74e9c3b778d9ccbd97ee329f0)

audio: add QCOM supported audio channels

Change-Id: Id29cb6949e137be8fb71d8d45e8e12bc47795f40
(cherry picked from commit 2fe37a40228c97e6f3b0575d94d4ec50b4dde1d6)

system/core: Add Qcom specific audio flags

- Support for Tunnel Mode Playback
- Reserve the LPA and VOIP_RX flags

Change-Id: Ifcbeb2a28feb86b030f48010a8a4e9cda8629e5b

Add ifdefs for QCOM enhanced features

Change-Id: Idefa831ecb4fdb881c990ba02ab4ab0ab7871986

audio: fix build break for non QCOM

Output:
error: 'AUDIO_DEVICE_IN_ANC_HEADSET' was not declared in this scope
error: 'AUDIO_DEVICE_IN_FM_RX' was not declared in this scope
error: 'AUDIO_DEVICE_IN_FM_RX_A2DP' was not declared in this scope
error: 'AUDIO_DEVICE_IN_PROXY' was not declared in this scope

Change-Id: Ie18c623303b944544b68eecca6208607d54b1c9a

Fix audio recording for ICS audio blobs

This fixes audio recording when ICS_AUDIO_BLOB is set because
AUDIO_DEVICE_BIT_IN was not used with ICS. Add #ifdefs to use the old checks
again.

Change-Id: I33b37e74d33fed7ab0bc2af9907e07d799b0ec0e

Merge branch 'kk-devel' of git://github.com/codefireXperiment/system_core into kk-devel-qcom

camera: change camera node permissions and add certain parameters.

Change-Id: Ia68160601c2b2ba3eebde9963b3972f2a09ff84a

Camera: Adds burst camera message type

Change-Id: I5ae041ae6062367abd8f8f59879846ae4ef3f72b
Signed-off-by: Solaiyappan Saravanan <saravanan.s@ti.com>
Signed-off-by: Emilian Peev <epeev@mm-sol.com>
Signed-off-by: Vicky Martinez-DeFrain <a0869710@ti.com>
Signed-off-by: Daniel Levin <dendy@ti.com>

Add RAW burst message

Change-Id: I5b42c66485151d1ba9eea8fbe58d334c2a892c24
Signed-off-by: Tyler Luu <tluu@ti.com>
Signed-off-by: Vladimir Petrov <vppetrov@mm-sol.com>
Signed-off-by: Daniel Levin <dendy@ti.com>

camera: Add new commands to compatibility block

Change-Id: I2952963661abf17f55eca811a8d4e8fc87933df0

Camera: Extend few data structures for QCom features.

Add message type for STATS_DATA and also the commands
which the application sends to start/stop histogram.
Also add few members to the face structure to extend
the face detection feature.

Change-Id: I3cc1c99ce40b58a029b1e048e6f84265833ac372

Camera: Adds meta data message and commands

- This change adds support for meta
  data type notification messages and
  commands.

Change-Id: I4d19254be90ac43a40e7d02d74a3c7c1a2bad336

Camera: Add meta data types for meta data callback

Add meta data callback types in order to reuse same callback
path for diffrent data types.

Change-Id: If8c6079c8a9a1fa7b3e708b6c5d9d04240509e2e

Camera: Adds longshot commands

- This change adds two new camera commands
  for enabling/disabling longshot mode.

CRs-Fixed: 514199
Change-Id: I47e4211ca0306347b6546707ed43b90ee3693060

Camera: Adds auto HDR Metadata type

- This type is used during auto HDR
  Metadata callbacks.

FM Radio: Add support for FM Radio in Android

Creating interface and framework for using FM Radio
RX and TX from different vendors.

Change-Id: I1a71aed01bfffdddfabf1cdfbfa3707cb1ed016b
Signed-off-by: Benn Porscke <benn.porscke@stericsson.com>

fmradio: cleanup QCOM_HARDWARE/STE_FM defs and ifdef

Change-Id: I00b5e6536511b3bedee6105bf010ee2b5f2e36ac

qcom-fm: audio: Add support for FM feature

-Define audio stream for FM
-Define audio source for FM RX and FM RX A2DP

Change-Id: If24e4c32916f6614e3367b4c9f2cd828562e0347

system/core: New stream type and flag for incall music delivery

- Add new stream type and flag for incall music delivery

Change-Id: I54d0d820d2dbb888d2e0cebdca63be2856eb00d8

system/core: Add tunnel format frame size

Add tunnel mode formats frame sizes to audio.h. This ensures frame
size definition in one place.

Change-Id: Ia01cb4cba003e538a53aaa18330ef860367859c1

audio: Add support tunnel mode recording

Support for tunnel recording

Change-Id: I8e4a4ce4cde23296beb783c7d678db1fa8936af1

audio: add EVRCWB EVRCB to supported audio formats

 compressed format should also include EVRCWB and EVRCB

 CRs-Fixed: 516138

Change-Id: I64f40d3380cb4fa055e0c3d79db3acf57929405c

system/core: Add support for EVRCNW audio format

This change is needed to support EVRCNW audio format.

Change-Id: I161c2c24ca764ed291f59d17d0a2be443818a7aa

Fix audio flags ifdeffing for qcom

Change-Id: I8183eaabe9ca9951f06256dfc761617f7c38b3d4

Revert "qcom-fm: audio: Add support for FM feature"

This reverts commit efa61acad6d546bac3f4886d38ff932eda4807a2.

Change-Id: I1c12a4ffb4ffdefe82b1c45fefa27ef079c71ac2

Revert "fmradio: cleanup QCOM_HARDWARE/STE_FM defs and ifdef"

This reverts commit c88de9fab033c4428f38a2be50ddb97eea66b8b9.

Change-Id: Iaf802c5af7256068a7d80cda53afca3b467748a6

Revert "FM Radio: Add support for FM Radio in Android"

This reverts commit 1e07014af2319f08c128c7702251c42e71742edb.

Change-Id: Ife5d06b4b4d65635d8c0d4d191392eb55f313243

system/core: Add MSM specific formats, devices and channels.

- Add support for MSM formats, devices and channels

Change-Id: I0f613e25ae7e5bafa126ab582551807711ab9db6
(cherry picked from commit 3535a5eafaa700ae58d44c43c4491f3fbb90e060)
(cherry picked from commit d725c0473b0c7f51d157b8722131ed7b45f878d7)
(cherry picked from commit 8d43d24d91e7bcc8daef40c6e9f99fd8dcd23266)

audio: Fix submix output device check.

-AUDIO_DEVICE_IN_FM_RX is incorrectly matched
 with AUDIO_DEVICE_OUT_REMOTE_SUBMIX because
 method audio_is_remote_submix_device is not
 checking for AUDIO_DEVICE_BIT_IN.

-Fix is to add AUDIO_DEVICE_BIT_IN while doing
 the check for AUDIO_DEVICE_OUT_REMOTE_SUBMIX.

CRs-Fixed: 566837

Change-Id: I47ca3bd151da848a444d4bcf83a56e866f20d4f7
(cherry picked from commit f8573b76d6c03e1a9eff34e093056a810f898509)
(cherry picked from commit ae982a488c68e0cd06622e7ee7a31fddb1f4d131)

audio: remove QCOM_FM_ENABLED ifdefs

* CM is using a different ifdef here that enables these by default.

Change-Id: I07249d1c3555446238d846901481b13634967aab

audio: Expose a few things previously under QCOM_HARDWARE

 * Allow everyone to use a few of these device types without
   setting QCOM_HARDWARE. Currently there is qute a mess due
   to the way QC is handling branches, when we figure out a
   good solution this can be reverted.

Change-Id: I75447a21ad1cf26e9683d2eac488a1b1238e5adb

Fix the build for devices with ICS/MR0_AUDIO_BLOB

The previous commit only exposed AUDIO_DEVICE_IN_ANC_HEADSET
and AUDIO_DEVICE_IN_PROXY if not defining this.

Change-Id: I7b644bb022f32fd978a85e003a97cbf27a17c809

Update the rc's

Another minor update, call init.cfx.rc, that may help a bit ;D

Test Plan: see if it builds and works on kk-devel then merge

Reviewers: synergy, jriordan001, anders3408, donald.munn

Differential Revision: http://review.codefirex.com/D149